# ABOUT US{-}

**NM-INBRE (New Mexico IDeA Networks of Biomedical Research Excellence):**

NM-INBRE Champions biomedical and community based research excellence in the state of New Mexico through the development of innovative, supportive and sustainable research environments for faculty and students, community engaging health initiatives, while building a network of lead scientists and educators at the state, regional and national level.
 
Funded by the Institutional Development Award (**IDeA**) of the National Institutes of Health (**NIH**) & National Institute of General Medical Sciences (**NIGMS**)  Grant # P20GM103451 

**NCGR (National Center for Genome Research):** 

Located in Santa Fe, New Mexico, the National Center for Genome Resources is a not-for-profit research institute that innovates, collaborates, and educates in the field of genomic data science. As leaders in DNA sequence analysis, we partner with government, industry, and academia to drive biological discovery in all kingdoms of life. 

NCGR operates NM-INBRE's Sequencing and Bioinformatics Core (SBC).  Through this partnership we offer the NM-INBRE SBC Pilot Award, which is a funding opportunity primarily for New Mexico researchers through which NCGR can help you with your research. 

## SBC PILOT AWARD RFP{-}

The New Mexico IDeA Networks of Biomedical Research Excellence (NM-INBRE) Sequencing and Bioinformatics Core (SBC) invites you to apply for a pilot project award to drive your research, publications and grants!

Award amount varies depending on various factors including your organization's affiliation with INBRE, RAIN or NM-INBRE.  Award may require a co-contribution. Please reach out to inbre@ncgr.org for more information or complete an application!

## How to Apply:{-} 

Submit proposal via this webform: [NM-INBRE SBC Pilot Award Application](https://docs.google.com/forms/d/e/1FAIpQLScpoBLtsMdId8wDGZ2IqXRg-3C54JQQWNy3skT7UTShUH4JZw/viewform)

NOTES:
Proposals from ‘non’ NM-INBRE investigators will require a co-contribution to foster state, regional and national INBRE collaborations.  Funds spent towards sequencing through NCGR or our partner can count towards this co-contribution.  
Past winners may apply, but new applicants have priority if all other factors are equal.

On any material presented or published based on this work, acknowledgement of:
Funding provided by the NM-INBRE Sequencing and Bioinformatics Core (SBC) at NCGR through NIGMS IDeA-Award P20GM103451.

NM-INBRE SBC staff supporting the project and inclusion as co-authors. We will review and write sections of posters and papers.



Please let us know if you have any questions! Email us at inbre@ncgr.org


-Joann Mudge and Ethan Price 


