# SBC PILOT AWARD RFP{-}

The New Mexico IDeA Networks of Biomedical Research Excellence (NM-INBRE) Sequencing and Bioinformatics Core (SBC) invites you to apply for a pilot project award to drive your research, publications and grants!

Award amount varies depending on various factors including your organization's affiliation with INBRE, RAIN or NM-INBRE.  Award may require a co-contribution. Please reach out to inbre@ncgr.org for more information or complete an application!

## How to Apply{-} 

Submit proposal via this webform: [NM-INBRE SBC Pilot Award Application](https://docs.google.com/forms/d/e/1FAIpQLScpoBLtsMdId8wDGZ2IqXRg-3C54JQQWNy3skT7UTShUH4JZw/viewform)

NOTES:

1.) Proposals from ‘non’ NM-INBRE investigators will require a co-contribution to foster state, regional and national INBRE collaborations.Funds spent towards sequencing through NCGR or our partner can count towards this co-contribution.  

2.) Past winners may apply, but new applicants have priority if all other factors are equal.

3.) On any material presented or published based on this work, acknowledgement of:

+ Funding provided by the NM-INBRE Sequencing and Bioinformatics Core (SBC) at NCGR through NIGMS IDeA-Award P20GM103451.

+ NM-INBRE SBC staff supporting the project and inclusion as co-authors. We will review and write sections of posters and papers.



Please let us know if you have any questions! Email us at inbre@ncgr.org


-Joann Mudge and Ethan Price 
