
# Single Cell RNA-seq Workshop

Application: Fill out this online application here: Single Cell Workshop Application

Space is limited!

Application and letter of recommendation due by midnight October 30th, 2023


## When

Nov 6 – 10, 2023 (5 days)

9 am – 4 pm


## Where

Online (by the National Center for Genome Resources (NCGR) Santa Fe, NM)


## Objective

Students will leverage their Unix and R command knowledge and become familiar with the SingleCellExperiment and Seurat R packages as well as an interactive Shiny web application to perform statistical metrics and data visualization for a variety of bioinformatic approaches to single cell sequencing analysis. 

## Audience


This advanced workshop is targeted towards undergraduate or graduate students in biology or related fields.  



## Workshop Rates

Applicant Category Cost

New Mexico Students & New Mexico Academic Researchers:
Free

All other students:
$1,000

IDeA state Researchers:
$1,250

Academic, Military, Government:
$1,750

Commercial:
$2,250

## Prerequisites

Unix, sequencing basics and other study guides will be provided upon acceptance.

What to expect upon acceptance

Email confirming acceptance into the internship program and further details.

## Logistics

The workshop will be conducted virtually using primarily Zoom as our conferencing platform.  We will also use a variety of other software and tools, and you will log onto NCGR’s Unix analysis server for the command line tools.  After the workshop, students can use our analysis server for their research or education purposes for up to one year.

Contact

Please contact Project Coordinator, Ethan Price with any additional questions you may have at eprice@ncgr.org and we look forward to your participation!

Sponsored by New Mexico IDeA Network for Biomedical Research Excellence (NM-INBRE).

# DE Workshop

Application: Fill out this online application here: DE Workshop Application

Space is limited!

Application due by midnight March 11th, 2024


## When

March 18 – 22, 2024 (5 days)

9 am – 4 pm


## Where

Online (by the National Center for Genome Resources (NCGR) Santa Fe, NM)


## Objective

Come learn about differential gene expression analysis in this virtual workshop that will teach you with hands-on analysis from start to finish. This differential expression workshop covers basic linux skills, quality control, read alignment, abundance estimation, differential expression analysis, visualization, and pathway analysis. Note that this workshop covers differential expression of bulk tissues (we cover single cell expression in a separate workshop). 

## Audience


This advanced workshop is targeted towards undergraduate or graduate students in biology or related fields.  


## Workshop Rates

Applicant Category Cost

New Mexico Students & New Mexico Academic Researchers:
Free

All other students:
$1,000

IDeA state Researchers:
$1,250

Academic, Military, Government:
$1,750

Commercial:
$2,250

## Prerequisites

Unix, sequencing basics and other study guides will be provided upon acceptance.

What to expect upon acceptance

Email confirming acceptance into the internship program and further details.

## Logistics

The workshop will be conducted virtually using primarily Zoom as our conferencing platform.  We will also use a variety of other software and tools, and you will log onto NCGR’s Unix analysis server for the command line tools.  After the workshop, students can use our analysis server for their research or education purposes for up to one year.

Contact

Please contact Project Coordinator, Ethan Price with any additional questions you may have at eprice@ncgr.org and we look forward to your participation!

Sponsored by New Mexico IDeA Network for Biomedical Research Excellence (NM-INBRE).

