
# Single Cell RNA-seq Workshop{-}

Application: Fill out the online application here: [Single Cell Workshop Application](https://forms.gle/xcfJYaHSDr4SQYUw9)


Application due by midnight TBD

## When{-}

TBD

9 am – 4 pm  

#### How much does it cost?{-}

[**Click here**](https://inbre.ncgr.org/ncgr-workshops/how-much-do-the-workshops-cost.html#how-much-do-the-workshops-cost) to get workshop rates. 

## Where{-}

Virtual (by the National Center for Genome Resources (NCGR) Santa Fe, NM)

## Topic Overview{-}

A typical RNA sequencing experiment captures transcriptional changes at the bulk tissue level representing a heterogenous mixture of cells and providing an aggregated expression result. By performing RNA sequencing on isolated single cells, one can pinpoint cellular expression and consider transcriptome sequences from individual cells to investigate, for example, cell lineage relationships, variability between cells and how a cell functions in its local environment. In this workshop, you will import single cell data, and cover topics such as normalization, quality control, dimensionality reduction, visualization, and data interpretation.

## Objective{-}

Students will leverage their Linux and R command knowledge to become familiar with the SingleCellExperiment, Seurat R packages, Loupe Browser, and an interactive Shiny web application to perform statistical metrics and data visualization for a variety of bioinformatic approaches to single cell sequencing analysis. 

## Audience{-}

This advanced workshop is targeted towards undergraduate or graduate students in biology or related fields.

## Prerequisites{-}

Reference material will be provided upon acceptance.

## Logistics{-}

The workshop will be conducted virtually using primarily Zoom as our conferencing platform. We will also use a variety of other software and tools, and you will log onto NCGR’s analysis server for the command line tools. After the workshop, students can use our analysis server for their research or education purposes for up to one year. Late applications will not be accepted. Participants will be accepted shortly after the deadline. If any questions arise while reviewing your application packet, we will contact you directly.  

Contact

Please contact Project Coordinator, Ethan Price with any additional questions you may have at inbre@ncgr.org and we look forward to your participation!

Sponsored by New Mexico IDeA Network for Biomedical Research Excellence (NM-INBRE).

