# Metagenomics Workshop{-}

Application: Fill out the online application here: [Metagenomics Workshop Application](https://forms.gle/Ai2psNtZJRvxygZZ9)


Application due by July 28, 2025


## When{-}

**August 04-08, 2025** (5 days)

9 am – 4 pm

#### How much does it cost?{-}

[**Click here**](https://inbre.ncgr.org/ncgr-workshops/how-much-do-the-workshops-cost.html#how-much-do-the-workshops-cost) to get workshop rates. 

## Where{-}

Virtual (via the National Center for Genome Resources (NCGR) Santa Fe, NM)


## Objective{-}

Learn how to use the UNIX command line, analytical workflows and public tools to independently analyze sequencing data plus how to visualize and render data using graphing tools.

This workshop covers analyses of 16s and whole genome shotgun metagenomic sequence data, including community analysis and assembly.


## Audience{-}


This workshop is targeted towards undergraduate or graduate students, and researchers in biology or related fields.  


## Prerequisites{-}

Unix, sequencing basics and other study guides will be provided upon acceptance.

What to expect upon acceptance

Email confirming acceptance into the internship program and further details.

## Logistics{-}

The workshop will be conducted virtually using primarily Zoom as our conferencing platform.  We will also use a variety of other software and tools, and you will log onto NCGR’s Unix analysis server for the command line tools.  After the workshop, students can use our analysis server for their research or education purposes for up to one year.

Late applications will not be accepted.  Selection Committee to select participants shortly after the deadline. If any questions arise while reviewing your application packet, we will contact you directly.
Contact

Please contact Project Coordinator, Ethan Price, with any additional questions you may have at inbre@ncgr.org and we look forward to your participation!

Sponsored by New Mexico IDeA Network for Biomedical Research Excellence (NM-INBRE).

