# Differential Expression Workshop{-}

Application: Fill out the online application here: 
[Differential Expression Workshop Application](https://forms.gle/aXG2StdRnSfKAcfA6)


Application due by October 13, 2025


## When{-}

October 20-24, 2025 (5 days)

9 am – 4 pm  

#### How much does it cost?{-}

[**Click here**](https://inbre.ncgr.org/ncgr-workshops/how-much-do-the-workshops-cost.html#how-much-do-the-workshops-cost) to get workshop rates. 

## Where{-}

Virtual (by the National Center for Genome Resources (NCGR) Santa Fe, NM)


## Objective{-}

Come learn about differential gene expression analysis in this virtual workshop that will teach you with hands-on analysis from start to finish. This differential expression workshop covers basic linux skills, quality control, read alignment, abundance estimation, differential expression analysis, visualization, and pathway analysis. Note that this workshop covers differential expression of bulk tissues (we cover single cell expression in a separate workshop). 

## Audience{-}

This advanced workshop is targeted towards undergraduate or graduate students in biology or related fields.  

## Prerequisites{-}

Unix, sequencing basics and other study guides will be provided upon acceptance.

What to expect upon acceptance

Email confirming acceptance into the internship program and further details.

## Logistics{-}

The workshop will be conducted virtually using primarily Zoom as our conferencing platform.  We will also use a variety of other software and tools, and you will log onto NCGR’s Unix analysis server for the command line tools.  After the workshop, students can use our analysis server for their research or education purposes for up to one year.

Selection Committee to select participants shortly after the deadline. If any questions arise while reviewing your application packet, we will contact you directly.

Contact

Please contact Project Coordinator, Ethan Price with any additional questions you may have at inbre@ncgr.org and we look forward to your participation!

Sponsored by New Mexico IDeA Network for Biomedical Research Excellence (NM-INBRE).
